### PR TITLE
Attempt to get working under PHP 8.1

### PR DESCRIPTION
**Pull request by nigelgbanks**
Upgrade symphony dependencies to ^4.4 to match up with Drupal 9

- Removed lock file
- Updated test matrix

For reasons behind removing the lock file, see:
https://islandora.slack.com/archives/CM5PPAV28/p1659631615201049
https://github.com/Islandora/documentation/issues/1908 (Removal approved)

Instead, we'll provide lock files in isle and Ansible deployments.

### CODE REVIEW

**Comment by nigelgbanks** [comment]
Gonna test with all the other services at once, will post my results.

**Comment by alxp** [comment]
@nigelgbanks This came up for discussion in the tech call today. I see it is still in Draft, is it good to go yet in your opinion?

**Comment by seth-shaw-asu** [comment]
@nigelgbanks, if we just remove the composer.lock file, I think this can go in. I don't believe you introduced any PHP 8 specific code that would prevent us from using it with either PHP 7 or 8.

**Comment by nigelgbanks** [comment]
@seth-shaw-asu & @alxp this is good to review now. I was successfuly able to install it with PHP 7.4, 8.0, and 8.1

**Review by seth-shaw-asu — APPROVED** [review]

**Comment by seth-shaw-asu** [comment]
@alxp, I forgot when I said I would take care of this one that it is a roblib repository. Could you go ahead and merge it?

**Pull request merged**
